// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmhabxgjckihgptoyupm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaGFieGdqY2tpaGdwdG95dXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTkzNzMsImV4cCI6MjA2MTY3NTM3M30.uTUGHNGTciVF0Cs_SKi7I2aElzzXLkmHQKjXeitkTOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});